name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0' # Adjust the flutter version if necessary
          dart-version: '2.19.4'
      - name: Install dependencies
        run: flutter pub get
      # Add other steps as needed

      # Uncomment to verify formatting
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .
